### ISSUE TITLE
How about hosting it on GH pages?

### ISSUE THREAD

**Issue by Khhs167** [ReCT-Lang/ReCT-Website#3]
Or dat not woerk?

**Comment by Khhs167** [comment]
Just for beta preview(not official hosting, just whilst it is under dev)

**Comment by WillTheDeveloper** [comment]
That should work

**Comment by WillTheDeveloper** [comment]
This has been followed up and now is being hosted on GH-pages. This can be found at: https://rect-programming-language.github.io/ReCT-Website/
